### PR TITLE
fix: cross platform support for --cache=fs

### PR DESCRIPTION
**Pull request by raffis**
## Current situation
pr #196 introduced a persistent chart cache by setting --cache=fs and will be part of v3.0.0.
However the implementation introduced does not work cross platform. Windows builds fail because unix syscalls were utilized which I didn't realized while reviewing and we do not invoke pr builds on any other platform than linux.

```
internal/fcache/fcache.go:47:16: undefined: syscall.Flock
internal/fcache/fcache.go:47:43: undefined: syscall.LOCK_EX
```

## Proposal
This pr refactors #196 to make it work on cross platform. I took as much as possible from the contribution but I had to ditch the entire fcache implementation and outsourced it into a cross platform lock lib.
I also put the cache mechanisms behind a common interface instead a combined manager instance. The logic is the same though as contributed.

### CODE REVIEW

**Review by rackep — APPROVED** [review]

**Comment by yorik** [comment]
@raffis sorry about that, never thought that somebody would use Windows.

From the first look I think that in the refactoring missing one thing: in fs cache it just takes the exclusive lock, but never checked if data is already there, so I think, it will re-download chart again and again.
Could you check that please?

**Comment by raffis** [comment]
>@raffis sorry about that, never thought that somebody would use Windows.

Windows doesn't have that high priority and its probably not really used. We also don't have any use for it. Although we do publish it for windows and I'd like to avoid introducing any platform restrictions if possible.

> From the first look I think that in the refactoring missing one thing: in fs cache it just takes the exclusive lock, but never checked > if >data is already there, so I think, it will re-download chart again and again.
> Could you check that please?

One it gets the exclusive lock it checks whether the chart exists on the fs, if it does it will make use of it.
https://github.com/DoodleScheduling/flux-build/pull/212/files#diff-8f7dfdd1d151e355dff81d86704d25d56edc8c438c394290ac4162af4eae142aR600-R604

I think this should do the job, happy too hear if this change works for you 👍🏻 or if there is any downside of that change.

**Comment by yorik** [comment]
Oh, I missed it because you moved it into helm.go. That should work, but AFAIK only on thread will be able to use the same helm chart in one time. Before the lock was held only during initial downloading and after that it was never used. But maybe there will be no speed penalty, let me check.

I'm testing it right now, one of the downsides the cache directory isn't created automatically for fs cache:
```
{"L":"ERROR","T":"2024-09-12T11:48:43.523Z","C":"action/action.go:131","M":"failed build helmrelease","namespace":"test","name":"flux-image-automation","error":"open /tmp/helm-cache/8e361beb%flux-image-automation%0.0.3.tgz.lock: no such file or directory","S":"github.com/doodlescheduling/flux-build/internal/action.(*Action).Run.func6\n\t/tmp/flux-build/internal/action/action.go:131\ngithub.com/alitto/pond.(*WorkerPool).executeTask\n\t/github/home/go/pkg/mod/github.com/alitto/pond@v1.9.2/pond.go:461\ngithub.com/alitto/pond.worker\n\t/github/home/go/pkg/mod/github.com/alitto/pond@v1.9.2/worker.go:13"}
```
I'll create the dir manually for the tests.

**Comment by raffis** [comment]
> I'm testing it right now, one of the downsides the cache directory isn't created automatically for fs cache:

Good catch, yes as for it is currently it expects the dir to be present, but I don't see a problem changing that behavior 👍🏻 , should be a quick fix.

**Comment by raffis** [comment]
> I've tested performance, there is some hit: all components using the same chart are indeed rendered continuously, but there is other stuff to do, so the slowdown is negligible: it's something between 1 and 2 seconds.
> 
> But I found actual issue, unrelated to this PR:
> 
> ```
>   - one document removed:
>     ---
>     apiVersion: source.toolkit.fluxcd.io/v1
>     kind: HelmRepository
>     metadata:
>     │ name: google-artifactory
>     │ namespace: flux-system
>     spec:
>     │ url: "oci://test/helm"
>     │ interval: 5m0s
>     │ provider: gcp
>     │ type: oci
>   
>     ---
>     apiVersion: source.toolkit.fluxcd.io/v1beta2
>     kind: HelmRepository
>     metadata:
>     │ name: google-artifactory
>     │ namespace: flux-system
>     spec:
>     │ url: "oci://test/helm"
>     │ interval: 5m0s
>     │ provider: gcp
>     │ type: oci
> ```
> 
> `apiVersion` got changed between 2 runs (we do render from a PR branch and from main and compare, there is no diff expected in this test). It's strange that `HelmRepository` api got changed only in one of them (both were rendered using the same binary). Any thoughts?


Interesting, yes so this is based on master which contains various changes for the new release including #205. My quick guess is there might be a race condition based on resource index and it depends which version came in first. 
Out tests succeeded so far but let me see if I can make out a bug there.

**Comment by raffis** [comment]
Thanks for the report @yorik. Its actually unrelated to master. But I think you are running into this problem https://github.com/DoodleScheduling/flux-build/pull/213

**Comment by yorik** [comment]
Right, thank you for fixing it!

**Comment by yorik** [comment]
I did a bit more tests here and it's good to go.
Thank you!

**Pull request merged**
