### PR TITLE
feat: Add Helm charts caching

### PR DESCRIPTION
**Pull request by yorik**
Add `--cache-enabled` flag to enable cache. Default is enabled.

Rewrote `internal/cache` module to download any chart just once and wait in concurrent builds.

Fixes: #166

### CODE REVIEW

**Comment by yorik** [comment]
@raffis, could you review this please?

With this caching any chart will downloaded only once per flux-build run. I think there is no need in cache expiration in flux-build.

It would be better to have shared cache between flux-build runs, maybe I'll implement it in the future.

**Review by raffis — COMMENTED** [review]
Nice work 🚀 

I am not sure about the --cache-size flag. According to the cache code its the number of items. Not sure if this even makes sense to let users modify. In my opinion this probably should just be unlimited as one could not even tell the order of which cache entries are added thus making it hard to reproduce across builds.

Also I believe caching should be enabled by default and there should be a bool flag to optionally disable it.

**Comment by yorik** [comment]
> Nice work 🚀
Thanks!
 
> I am not sure about the --cache-size flag. According to the cache code its the number of items. Not sure if this even makes sense to let users modify. In my opinion this probably should just be unlimited as one could not even tell the order of which cache entries are added thus making it hard to reproduce across builds.

I thought about that, but decided to do less changes. Done. I think, it would be ok to remove unused functions (Set, Get, Add, ItemCount, Clear, Delete), simplify test and remove the license. WDYT?

> Also I believe caching should be enabled by default and there should be a bool flag to optionally disable it.

Done.

I also changed the file name pattern because right now it's `---abcdef0123456789.tgz`, all the fields `pattern` tries to use from the `obj` are empty.


Please take another look.

**Comment by yorik** [comment]
I don't have permissions to merge, could you do that?

**Comment by raffis** [comment]
It will be released soon, likely tomorrow 👍🏻

**Pull request merged**
