### PR TITLE
feat: Add shared Helm cache, based on flock

### PR DESCRIPTION
**Pull request by yorik**
Shared file cache is designed to minimize Helm charts downloads from a CI which runs flux-build several times. The files will be located in `--cache-dir` with name based on helm chart name and version, disabled by default.

Also it caches repository.Downloader in memory to prevent excessive login calls.

### CODE REVIEW

**Comment by yorik** [comment]
@raffis could you please review this? It's greatly increases speed of our CI.

I thought about cleaner implementation using common `Cache` interface, but they are way too different.
Not sure if it should be disabled by default because it creates files and leave them after the run for the following runs to use, but that could interfere with different usage patterns.

**Review by raffis — COMMENTED** [review]
I do see the need for a persistent cache across builds but implementing some sort of two different cache mechanics looks odd to me (as you already pointed out).
Also that one would need to specify a path to enable the persistent cache seems not the common way how fs caches are handled in other toolings.

There should be either a common interface or I'm thinking of whether it just makes more sense to only keep the fs cache code and a flag called `--cache=[none|inmemory|fs]` while inmemory is the default (deprecating the --cache-enabled). --cache-dir would default to ~/.cache/flux-build. If --cache=inmemory is set the cachedir would be TEMPDIR/flux-build-(randstring) (and a defer call to clean it at the end. And even if it fails its in the system cache which will be purged anyways at some point).
inmemory should be the default as a persistent cache can intrododuce a bunch of other problems. For example if a chart is changed in the remote location. Not much we can do about that thats why inmemory should continue be the default (as it already is in this pr)

And while looking at this i think there is a problematic edge case (already introduced by the previous pr for the memory cache). If there is a chart with the same name and version but from different sources I think it will reuse the cached variant which is dangerous as it can be a completely different chart. With the fs cache this is even more likely to happen at some point as the cache would live over time.

**Comment by yorik** [comment]
> I do see the need for a persistent cache across builds but implementing some sort of two different cache mechanics looks odd to me (as you already pointed out). Also that one would need to specify a path to enable the persistent cache seems not the common way how fs caches are handled in other toolings.

For us it's 7m vs 18s to run our CI, we have >20 of clusters and if there is no persistent cache the CI attempts to download Helm charts are rate limited.

Specifying the path would gives more control as it runs in custom GitHub Runner, so there is no home to put the cache in.
 
> There should be either a common interface or I'm thinking of whether it just makes more sense to only keep the fs cache code and a flag called `--cache=[none|inmemory|fs]` while inmemory is the default (deprecating the --cache-enabled). --cache-dir would default to ~/.cache/flux-build. If --cache=inmemory is set the cachedir would be TEMPDIR/flux-build-(randstring) (and a defer call to clean it at the end. And even if it fails its in the system cache which will be purged anyways at some point). inmemory should be the default as a persistent cache can intrododuce a bunch of other problems. For example if a chart is changed in the remote location. Not much we can do about that thats why inmemory should continue be the default (as it already is in this pr)

Sounds good, I'll implement that.

> And while looking at this i think there is a problematic edge case (already introduced by the previous pr for the memory cache). If there is a chart with the same name and version but from different sources I think it will reuse the cached variant which is dangerous as it can be a completely different chart. With the fs cache this is even more likely to happen at some point as the cache would live over time.

I thought about that, but forgot to implement because we have only single source of charts. I think I could prefix the files with hash of URL of the registry. Should be good enough, WDYT?

**Comment by raffis** [comment]
> I thought about that, but forgot to implement because we have only single source of charts. I think I could prefix the files with hash of URL of the registry. Should be good enough, WDYT?
Yes that should do it (besides some edge cases which can't be covered).

**Comment by yorik** [comment]
@raffis could you please take another look?

I think it has clean design now.

**Comment by yorik** [comment]
I found a bug there, trying to fix it...

**Comment by yorik** [comment]
I fixed the bug and added Downloader caching. Now it should be optimal.
Please take a look.

**Review by raffis — APPROVED** [review]
This is excellent work @yorik 🥇

**Pull request merged**
